/* eslint-disable max-len,quotes */
const Labels = {
  DECISION: 'החלטה',
  EXPLANATION: 'הערות לשלב (מלל חופשי)',

  EXPLANATION_UTILITARIANISM: 'הערות לשלב (מלל חופשי)',
  EXPLANATION_KANT_GENERAL: 'הערות לשלב (מלל חופשי)',
  EXPLANATION_KANT_FORMULA: 'הערות לשלב (מלל חופשי)',
  EXPLANATION_ARISTO: 'הערות לשלב (מלל חופשי)',
  EXPLANATION_HOBBS: 'הערות לשלב (מלל חופשי)',
  EXPLANATION_LUKE: 'הערות לשלב (מלל חופשי)',
  EXPLANATION_ROLLS: 'הערות לשלב (מלל חופשי)',


  TITLE: 'שאלון דילמות מוסריות',
  FULL_NAME: 'שם מלא',
  ID: "מס' תעודת זהות",
  DESCRIPTION: 'תיאור דילמה אישית (עד 200 מילים בלבד)',
  DESCRIPTION_DETAILS: `נא לוודא שהדילמה היא: אישית (קרתה לך אישית ומנוסחת בגוף ראשון) + מוסרית`,
  OPTION_A: "מהי דרך הפעולה האפשריות מס' 1",
  OPTION_A_DETAILS: "למשל: לפטר את העובד, לבצע את הוראת הבוס, לחשוף את המידע בפני הקולגה וכו'.",
  OPTION_B: "מהי דרך הפעולה האפשריות מס' 2",
  OPTION_B_DETAILS: "למשל: לא לפטר את העובד, לא לבצע את הוראת הבוס, לא לחשוף את המידע בפני הקולגה וכו'.",
  WHICH_OPTION: `איזו מדרכי הפעולה הנ"ל (דפ"א מס' 1 או דפ"א מס' 2) בחרת בזמן אמת`, // Which Option did you end up choosing?
  CHOOSING_OPTIONS: [
    `דפ"א מס' 1`,
    `דפ"א מס' 2`,
  ],
  OPTION_A_VALUES: `אילו ערכים ראויים מנמקים את הבחירה בדפ"א מס' 1 `, // Whichvalues doesoption Arepresent?
  OPTION_A_VALUES_HINT: `ניתן לסמן יותר מערך אחד.`, // You can select more than one.
  OPTION_B_VALUES: `אילו ערכים ראויים מנמקים את הבחירה בדפ"א מס' 2 `, // Which values does option B represent?
  OPTION_B_VALUES_HINT: `ניתן לסמן יותר מערך אחד. אם יש ערכים שסומנו לגבי דפ"א 1 שרלוונטיים גם לדפ"א 2 - ניתן לסמן גם אותם.`,
  VALUES_OPTIONS: [
    'בריאות \\ חיי אדם',
    'חירות',
    'כבוד האדם',
    'הגינות (כולל אמינות, יושרה, אמון)',
    'שוויון הזדמנויות',
    'צדק חלוקתי \\ תוצאתי',
    'כיבוד החוק',
  ],
  OPTIONS_WORTHY: 'בדיקת ביניים - האם משני צידי הדילמה ישנם ערכים ראויים',
  WHICH_OPTION_ANALYZE: `איזו מהדפ"אות הנ"ל (דפ"א מס' 1 או דפ"א מס' 2) אני בוחר/ת לנתח במטלה`,
  WHICH_OPTION_ANALYZE_HINT: `יש לבחור אחת משתי הדפ"אות, ולנתח בעקביות רק אותה לאורך כל השלבים.`,
  NEXT: 'הבא',
  PREVIOUS: 'קודם',
  COMPLETE: 'בוצע',
  SAVE: 'שמור טופס',
  LOAD: 'טען טופס קיים',
  POSITIVE: 'לפי שלב זה ראוי לבצע את הדפ"א שבחרת',
  NEGATIVE: 'לפי שלב זה לא ראוי לבצע את הדפ"א שבחרת',

  FEEDBACK: 'משוב מילולי - עד כמה היה לך פשוט ונוח להשתמש בכלי הניתוח לצורך הכרעה בדילמה',

  FEEDBACK_UTILITARIANISM: 'משוב מילולי - עד כמה היה לך פשוט ונוח להשתמש בכלי הניתוח התועלתנות לצורך הכרעה בדילמה',
  FEEDBACK_KANT_GENERAL: 'משוב מילולי - עד כמה היה לך פשוט ונוח להשתמש בכלי הניתוח קאנט - נוסחת החוק הכללי לצורך הכרעה בדילמה',
  FEEDBACK_KANT_FORMULA: 'משוב מילולי - עד כמה היה לך פשוט ונוח להשתמש בכלי הניתוח קאנט - נוסחת האדם כתכלית לצורך הכרעה בדילמה',
  FEEDBACK_ARISTO: 'משוב מילולי - עד כמה היה לך פשוט ונוח להשתמש בכלי הניתוח אריסטו - טבלת המידות לצורך הכרעה בדילמה',
  FEEDBACK_SUBJECTIVISM: 'משוב מילולי - עד כמה היה לך פשוט ונוח להשתמש בכלי הניתוח יום - סובייקטיביזם לצורך הכרעה בדילמה',
  FEEDBACK_HOBBS: 'משוב מילולי - עד כמה היה לך פשוט ונוח להשתמש בכלי הניתוח הובס - סימולציית קוד אתי לצורך הכרעה בדילמה',
  FEEDBACK_LUKE: 'משוב מילולי - עד כמה היה לך פשוט ונוח להשתמש בכלי הניתוח לוק - זכויות טבעיות לצורך הכרעה בדילמה',
  FEEDBACK_ROLLS: 'משוב מילולי - עד כמה היה לך פשוט ונוח להשתמש בכלי הניתוח רולס - צדק לצורך הכרעה בדילמה',


  UTILITARIANISM: `1. התועלתנות  `,
  UTILITARIANISM_EXPLANATION: 'בעלי עניין - אנשים בודדים או קבוצות המושפעים מהפעולה', // Please write briefly in 3 stages
  HOW_SIMPLE_UTILITARIANISM: 'משוב מספרי - עד כמה היה לך פשוט ונוח להשתמש בכלי הניתוח "התועלתנות" לצורך הכרעה בדילמה', // Technical feedback - how would you simple and easy to use analysis tool "utilitarianism" In order to rule dilemma
  VERY_SIMPLE: 'בכלל לא פשוט ולא נוח',
  NOT_SIMPLE: 'מאוד פשוט ונוח',
  PEOPLE_OF_INTEREST: 'א. מיהם בעלי העניין (אנשים בודדים או קבוצות המושפעים מהפעולה)',
  PEOPLE_OF_INTEREST_SUMMARY: 'מיהם בעלי העניין (אנשים בודדים או קבוצות המושפעים מהפעולה)',
  NAME: 'שם',
  NUMBER_OF_PEOPLE: 'מספר אנשים',
  DAMAGE_OR_BENEFIT: 'ב. כמות התועלת \\ הנזק מהפעולה לכל בעל עניין ',
  DAMAGE_OR_BENEFIT_SUMMARY: 'כמות התועלת \\ הנזק מהפעולה לכל בעל עניין ',
  DAMAGE: 'נזק',
  BENEFIT: 'תועלת',
  GRADE_UTILITARIANISM: 'ג. תועלת / נזק מצטברים לכל בעלי העניין ביחד',
  DAMAGE_OR_BENEFIT_GRADE: 'כמות התועלת או הנזק לכל אדם בודד במספר',
  ACCUMULATED_GRADE_UTILITARIANISM: 'ג. תועלת / נזק מצטברים לכל בעלי העניין ביחד',
  PERSON_OF_INTEREST: 'בעל עניין',

  KANT_GENERAL: `2. קאנט - נוסחת החוק הכללי `,
  KANT_GENERAL_EXPLANATION: 'נא לכתוב בקצרה ב 2 שלבים',
  HOW_SIMPLE_KANT_GENERAL: `משוב מספרי - עד כמה היה לך פשוט ונוח להשתמש בכלי הניתוח "קאנט - נוסחת החוק הכללי" לצורך הכרעה בדילמה`,
  PRACTICAL_RULE_FORMULATION: 'א. ניסוח כלל מעשי',
  GENERAL_RULE_FORMULATION: 'ב. ניסוח חוק כללי',
  GRADE_KANT_GENERAL: 'ג. האם חוק כזה רצוי',
  ON_ONE_HAND: 'מצד אחד',
  ON_OTHER_HAND: 'מצד שני',
  NO: 'לא',
  YES: 'כן',

  KANT_FORMULA: `3. קאנט - נוסחת האדם כתכלית `,
  KANT_FORMULA_EXPLANATION: 'נא לכתוב בקצרה ב 3 שלבים',
  HOW_SIMPLE_KANT_FORMULA: '[משוב מספרי - עד כמה היה לך פשוט ונוח להשתמש בכלי הניתוח "קאנט - נוסחת האדם כתכלית" לצורך הכרעה בדילמה',
  MEANS: 'מי משמש אמצעי',
  PURPOSE: 'מי משמש תכלית',
  KANT_PEOPLE_OF_INTEREST_TITLE: 'א. בעלי העניין (אנשים בודדים או קבוצות המושפעים מהפעולה)',
  KANT_DECISION: `ב. האם ניתנה לבעלי העניין הזדמנות להבין את הפעולה בטרם ביצועה ולהסכים לה?`,
  KANT_DECISION_SUMMARY: `האם ניתנה לבעלי העניין הזדמנות להבין את הפעולה בטרם ביצועה ולהסכים לה?`,
// (לא=התייחסות לבעל העניין כאמצעי)
// (כן=התייחסות לבעל העניין כתכלית)

  KANT_ACC_GRADE_ROW_TITLE: 'ג. ביחס לכלל בעלי העניין במצטבר: האם בביצוע הפעולה התייחסו אליהם יותר כאמצעי או יותר כתכלית',
  NO_MEANS: 'לא (אמצעי)',
  YES_PURPOSE: 'כן (תכלית)',
  KANT_MORAL: 'תכלית',
  KANT_NOT_MORAL: 'אמצעי',

  ARISTOTLE: `4. אריסטו - טבלת המידות `,
  ARISTOTLE_HINT: 'נא לסמן בכל שורה לאיזו מידה הדפ"א מתאימה יותר',
  ARISTOTLE_SCROLL: 'יש לסמן תשובה אחת בלבד בכל שורה. שימו לב לאופציה הרביעית - "מידה זו לא רלוונטית". גלול שמאלה אם אינך רואה ארבע אפשרויות',
  ARISTO_ACC_GRADE_ROW_TITLE: 'תוצאה',
  HOW_SIMPLE_ARISTOTLE: 'משוב מספרי - עד כמה היה לך פשוט ונוח להשתמש בכלי הניתוח "אריסטו - טבלת המידות" לצורך הכרעה בדילמה',

  INDIFFERENCE1: 'אדישות',
  INDIFFERENCE_HINT1: 'חוסר אכפתיות',
  COURAGE1: 'מוגות לב',
  COURAGE_HINT1: 'פחדנות',
  SHAME1: 'שפלות רוח',
  SHAME_HINT1: 'התבטלות עצמית מול אחרים',
  GREED1: 'ותרנות',
  GREED_HINT1: 'נטייה לוותר בקלות רבה מדי על דבר מה, לטובת מישהו אחר שאינו ראוי לכך',
  GENEROSITY1: 'קמצנות',
  GENEROSITY_HINT1: 'חיסכון מוגזם במשאבים',
  ENDURANCE1: 'סגפנות',
  ENDURANCE_HINT1: 'השקעת מאמץ מוגזם ללא הצדקה',
  ARROGANCE1: 'ענוותנות',
  ARROGANCE_HINT1: 'צניעות מוגזמת ללא הצדקה',
  INNOCENCE1: 'תמימות',
  INNOCENCE_HINT1: 'להיות מושפע לרעה ממניפולציה של אחרים',

  INDIFFERENCE2: 'מתינות',
  INDIFFERENCE_HINT2: 'אכפתיות במידה הנכונה',
  COURAGE2: 'אומץ לב',
  COURAGE_HINT2: 'תעוזה במידה הנכונה',
  SHAME2: 'בושה',
  SHAME_HINT2: 'מתן כבוד לאחרים במידה הנכונה',
  GREED2: 'צדק',
  GREED_HINT2: 'היכולת לחלק לכל אחד את מה שמגיע לו במידה הנכונה',
  GENEROSITY2: 'נדיבות',
  GENEROSITY_HINT2: 'שימוש במשאבים במידה הנכונה',
  ENDURANCE2: 'כוח סבל',
  ENDURANCE_HINT2: 'השקעת מאמץ במידה הנכונה',
  ARROGANCE2: 'גדלות נפש',
  ARROGANCE_HINT2: 'התייחסות לאחרים כאל שווי מעמד ובגובה העיניים',
  INNOCENCE2: 'זהירות',
  INNOCENCE_HINT2: 'היכולת שלא להיות מושפע לרעה ממניפולציות של אחרים, ולא להשפיע על אחרים על ידי מניפולציות',

  INDIFFERENCE3: 'כעסנות',
  INDIFFERENCE_HINT3: 'יותר מדי אכפתיות או מעורבות רגשית הגורמות לכעס מיותר',
  COURAGE3: 'העזה (נמהרות)',
  COURAGE_HINT3: 'תעוזה מוגזמת ופזיזה הגורמת סיכון או נזק מיותרים',
  SHAME3: 'עזות פנים',
  SHAME_HINT3: 'חוצפה כלפי אחרים',
  GREED3: 'חמדנות',
  GREED_HINT3: 'תאוות בצע, נטייה לקחת דבר מה השייך למישהו אחר',
  GENEROSITY3: 'בזבזנות',
  GENEROSITY_HINT3: 'בזבוז מוגזם של משאבים',
  ENDURANCE3: 'פנקנות',
  ENDURANCE_HINT3: 'השקעת מעט מדי מאמץ ללא הצדקה',
  ARROGANCE3: 'יהירות',
  ARROGANCE_HINT3: 'התנשאות ללא הצדקה',
  INNOCENCE3: 'ערמומיות',
  INNOCENCE_HINT3: 'השפעה מניפולטיבית על אחרים',

  MISSING: 'המידה החסרה',
  PRESENT: 'המידה האמצעית',
  EXCESSIVE: 'המידה היתרה',
  NOT_RELEVANT: 'מידה זו לא רלוונטית',
  NOT_RELEVANT_LUKE: 'זכות זו לא רלוונטית',
  NOT_RELEVANT_ROLLS: 'עקרון זה לא רלוונטי',
  OP_A: `דפ"א מס' 1`,
  OP_B: `דפ"א מס' 2`,

  SUBJECTIVISM: `5. יום - סובייקטיביזם `,
  SUBJECTIVISM_EXPLANATION: 'הערות',
  HOW_SIMPLE_SUBJECTIVISM: 'משוב מספרי - עד כמה היה לך פשוט ונוח להשתמש בכלי הניתוח "יום - סובייקטיביזם" לצורך הכרעה בדילמה',
  MAIN_FACTS: 'נא לכתוב את כל העובדות המרכזיות בדילמה ',
  BETTER_OPTION: 'הכרעה עפ"י הרגש',
  BETTER_OPTION_HINT: 'איזו מבין שתי ההחלטות תגרום לי "לישון יותר בשקט"? ',

  HOBBS: `6. הובס - סימולציית קוד אתי `,
  HOBBS_EXPLANATION: 'נא לכתוב בקצרה',
  HOBBS_HINT: 'אם יש קוד בארגונך - יש להכריע האם הדפ"א הנבחרת מוסרית ע"י איזון בין ערכי הקוד הקיים. אם לא - יש להתייחס לערכים שלדעתך אמורים להופיע בקוד, ולהכריע באותו אופן.',
  HOW_SIMPLE_HOBBS: 'משוב מספרי - עד כמה היה לך פשוט ונוח להשתמש בכלי הניתוח "הובס - סימולציית קוד אתי" לצורך הכרעה בדילמה',
  VALUE: 'ערך',
  HOBBS_BETTER_OPTION: 'אפשרות טובה יותר',
  ETHICAL_CODE_VALUES: 'ערכים בקוד האתי',
  WHICH_OPTION_BETTER: 'איזו משתי הדפ"אות מקיימת טוב יותר כל ערך?',
  FINAL_CHOICE_HOBBS: 'בשיקלול מצטבר של כל הערכים בקוד האתי - איזו דפ"א מקיימת טוב יותר את הקוד האתי?',

  LUKE: `7. לוק - זכויות טבעיות `,
  LUKE_EXPLANATION: 'זכויות טבעיות', // Natural rights
  LUKE_HINT: 'יש לסמן רק את הזכויות הטבעיות שהדפ"א הנבחרת מקיימת אותן יותר מהדפ"א השניה. בשורת ה"אחר" יש לכתוב את ההכרעה: האם הדפ"א הנבחרת מוסרית.', // Mark only the natural rights Shdf"a team fulfills them more Mhdf"a second. At the Other "has to write the truth: Hdf"a team moral.
  LUKE_CHOICES: [
    'א. חיים',
    'ב. בריאות',
    'ג. חירות',
    'ד. קניין (כפוף לשני הסייגים: אי השחתה + אפשרות שימוש לאחרים)',
    'אף אחת מהזכויות הטבעיות הנ"ל אינה רלוונטית',
    `אַחֵר`, // Other
  ],
  HOW_SIMPLE_LUKE: 'משוב מספרי - עד כמה היה לך פשוט ונוח להשתמש בכלי הניתוח "לוק - זכויות טבעיות" לצורך הכרעה בדילמה',
  FINAL_CHOICE_LUKE: 'בשיקלול מצטבר של כל הזכויות הטבעיות - איזו דפ"א מקיימת אותן טוב יותר?',
  NATURAL_RIGHTS: 'זכויות טבעיות',
  LUKE_BETTER_OPTION: 'איזו משתי הדפאות מקיימת טוב יותר כל זכות טבעית',
  LUKE_TABLE_COLUMN2_TITLE: 'איזו משתי הדפאות מקיימת טוב יותר כל זכות טבעית',
  LIFE: 'א. חיים',
  HEALTH: 'ב. בריאות',
  FREEDOM: 'ג. חירות',
  PROPERTY: 'ד. קניין (כפוף לשני הסייגים: אי השחתה + אפשרות שימוש לאחרים)',
  OTHER: 'אַחֵר',
  OTHER_VALUE: 'ערך אחר',
  JUSTICE_RIGHTS: 'עקרונות צדק',

  ROLLS: `8. רולס - צדק `,
  ROLLS_EXPLANATION: 'צדק',
  ROLLS_BETTER_OPTION: 'איזו משתי הדפ"אות מקיימת טוב יותר כל עקרון צדק',
  ROLLS_FINAL_CHOICE: 'בשיקלול מצטבר של כל עקרונות הצדק - איזו דפ"א מקיימת אותם טוב יותר? ',
  ROLLS_TABLE_COLUMN2_TITLE: 'איזו משתי הדפאות מקיימת טוב יותר כל עקרון צדק',
  ROLLS_HINT: 'יש לסמן רק את עקרונות הצדק שהדפ"א הנבחרת מקיימת אותם יותר מהדפ"א השניה. בשורת ה"אחר" יש לכתוב את ההכרעה: האם הדפ"א הנבחרת מוסרית.',
  ROLLS_CHOICES: [
    'א. חירות',
    'ב. שוויון הזדמנויות',
    'ג. פער',
    `אַחֵר`,
  ],
  EQUALITY: 'ב. שוויון הזדמנויות',
  GAP: 'ג. פער',
  FREEDOM_ROLLS: 'א. חירות',
  HOW_SIMPLE_ROLLS: 'משוב מספרי - עד כמה היה לך פשוט ונוח להשתמש בכלי הניתוח "רולס - צדק" לצורך הכרעה בדילמה',

  SUMMARY: 'סיכום',
  CONCLUSIONS: 'מסקנות ותובנות', // Conclusions and Insights
  CONCLUSIONS_HINT: `יש לכתוב בקצרה תובנות / מסקנות מהשוואה בין תוצאת ניתוח הדילמה לבין הפעולה שביצעת בזמן האמת.`,  // Have to write a brief insight into \ Conclusions A comparison of the results of analyzes of the dilemma and the action you performed in real time
  CORRECTIVE: 'לאור הניתוח שביצעת לעיל - האם הפעולה שביצעת בזמן אמת היא הפעולה המוסרית?', // In view of the above analysis that you made - whether real-time corrective action is moral action?
  // MICHAEL NOTES - THIS SHOULD BE AUTOMATICALLY CALCUALATED AND SHOWN TO THE USER AND NOT A QUESTION OF CHOICE
  MORAL_APPROACH: 'גישה מוסרית',
  MORAL_APPROACH_TEST_RESULT_LABEL: 'האם החלופה בה בחרת היא מוסרית?',
  CHOSEN_MORAL: 'החלופה בה בחרת היא מוסרית',
  CHOSEN_IMMORAL: 'החלופה בה בחרת לא מוסרית',
  TECHNICAL_FEEDBACK: 'משוב מילולי כללי על טופס הגשת המטלה - עד כמה היה פשוט ונוח לבצע את המטלה ע"י הטופס האלקטרוני', // [General technical feedback form on assignment - how was simple and convenient to perform the task by e-form]
  TECHNICAL_FEEDBACK_HINT: 'אנא פרטו באופן חופשי כל דבר שיוכל לעזור לנו לשפר את הטופס למחזורים הבאים.', // Please Preto freely anything that could help us improve these cycles form.

  RESPONSE_SUBMITTED: 'תגובתך נקלטה. נא לשמור על הקובץ שהורד לעיון.',
  REQUIRED: 'זהו שדה חובה',
  FIX_ERRORS: 'אנא תקן את השגיאות לפני שתמשיך.',
  DILEMMA: 'דִילֶמָה',
};
/* eslint-enable max-len,quotes */

export default Labels;
